general {
  hide_cursor = true
  no_loading_bar = true
}

background {
  monitor =
  color = rgba(08052bf2)
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +'%H:%M')"
  color = rgba(ffffffff)
  font_size = 64
  font_family = Cascadia Code
  position = 0, 80
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +'%A, %d %B %Y')"
  color = rgba(ffffffcc)
  font_size = 18
  font_family = Cascadia Code
  position = 0, 30
  halign = center
  valign = center
}

input-field {
  monitor =
  size = 260, 50
  outline_thickness = 2
  dots_size = 0.25
  dots_spacing = 0.3
  dots_center = true
  outer_color = rgba(5294e2ff)
  inner_color = rgba(08052be6)
  font_color = rgba(ffffffff)
  fade_on_empty = false
  placeholder_text = <span foreground="#b0b5bd">Locked</span>
  hide_input = false
  check_color = rgba(5294e2ff)
  fail_color = rgba(e53935ff)
  position = 0, -40
  halign = center
  valign = center
}
