splash = false

wallpaper {
  monitor = HDMI-A-1
  path = /home/mfm/Desktop/005_Eerie_fungal_forest_with_giant_glowing_s.png
  fit_mode = cover
}

wallpaper {
  monitor = DP-1
  path = /home/mfm/Desktop/005_Eerie_fungal_forest_with_giant_glowing_s.png
  fit_mode = cover
}

wallpaper {
  monitor = DP-2
  path = /home/mfm/Desktop/005_Eerie_fungal_forest_with_giant_glowing_s.png
  fit_mode = cover
}
